@base = http://localhost:8080/api/tickets/v1/chart

GET  {{base}}/chart1
content-type: application/json

{}

###
GET  {{base}}/chart2
content-type: application/json

{}

###
GET  {{base}}/chart3
content-type: application/json

{}

###
